languageCode = "en-uk"
title = "HW/SW codesign"

baseurl = "https://kuleuven-diepenbeek.github.io/course_hwswcodesign/"
# fix for subdir baseurl, see https://discourse.gohugo.io/t/issue-when-baseurl-have-subdirectory/4088/7
RelativeURLs=true
CanonifyURLs=true

theme = "hugo-theme-learn"
publishDir = "docs"
enableEmoji = true
enableRobotsTXT = true
pygmentsCodefences = true

# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true


# Blackfriday was removed in Hugo v0.100.0.
[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.goldmark.renderer]
    unsafe= true


# for new Hugo 0.6x, markup changed to CommonMark.
# [markup]
#   defaultMarkdownHandler = "blackfriday"
#   [markup.blackFriday]
#     skipHTML = false
#   [markup.highlight]
#     anchorLineNos = false
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineAnchors = ""
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = true
#     style = "monokai"
#     tabWidth = 4
# 
# [blackfriday]
#   hrefTargetBlank = true

[taxonomies]
    tag = "tags"

[params]
    disableComments = true
    themeVariant = "kul"
    disableInlineCopyToClipBoard = true
    ordersectionsby = "weight"
    disableLandingPageButton = true # Disable the "Home" link in the navigation menu

# see https://learn.netlify.com/en/basics/configuration/
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Author]
  name = "Jo Vliegen"
  email = "<i>fname</i>.<i>lname</i>A T<i>kuleuven.be</i>"

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> Toledo"
identifier = "tol"
url = "https://p.cygnus.cc.kuleuven.be/webapps/blackboard/execute/announcement?method=search&context=course&course_id=_1176295_1&handle=cp_announcements&mode=cpview"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> ECTS Sheet"
identifier = "stud"
url = "https://studiegidswww.uhasselt.be/opleidingsonderdeel.aspx?a=2023&i=3468&n=4&t=04"
weight = 1
